"""filepath

Revision ID: 04a1d1906601
Revises: 4ab9b545c736
Create Date: 2024-10-10 15:09:28.522136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a1d1906601'
down_revision = '4ab9b545c736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(), nullable=False))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
