"""url

Revision ID: 232e7ee96efc
Revises: 23436dd64b74
Create Date: 2024-12-27 12:07:15.757397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232e7ee96efc'
down_revision = '23436dd64b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(), nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
